# Path to the directory with the train data
train_dir: data_debug/train/

# Name of the file to save results
fname_to_save: data_debug/data_only_len3_tracks.npz

# Fraction of the validation subset of data
val_size: 0.2

# Random seed
random_seed: 13

# Debug mode
debug:
  debug_size: 5000

# distribution of tracks' lengths. Use '-1' for following dataset's initial distribution
distribution:
  len3: -1
  len4: 0
  len5: 0
  len6: 0

