# Path to the directory with the train data
train_dir: /Users/egor/prog/short_tracks/data_debug/train/

# Name of the file to save results
fname_to_save: train_dataset_vertex_eq_dist.npz

# Fraction of the validation subset of data
val_size: 0.2

# Random seed
random_seed: 13

# Debug mode
debug: False

# distribution of tracks' lengths. Use '-1' for following dataset's initial distribution
distribution:
  len3: 0.25
  len4: 0.25
  len5: 0.25
  len6: 0.25

